// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides formatting suggestions for documents to improve printing results.
 *
 * - getFormattingSuggestions - A function that generates formatting suggestions for a document.
 * - FormattingSuggestionsInput - The input type for the getFormattingSuggestions function.
 * - FormattingSuggestionsOutput - The return type for the getFormattingSuggestions function.
 */

import {ai, isAiEnabled} from '@/ai/genkit';
import {z} from 'genkit';

const FormattingSuggestionsInputSchema = z.object({
  documentType: z
    .string()
    .describe('The type of the document, e.g., Resume, Thesis, Contract, Report.'),
  formattingScore: z
    .number()
    .describe('A score (0-100) representing the document layout and structure.'),
  documentText: z
    .string()
    .describe('The text content of the document to analyze for formatting.'),
});
export type FormattingSuggestionsInput = z.infer<typeof FormattingSuggestionsInputSchema>;

const FormattingSuggestionsOutputSchema = z.object({
  suggestions: z
    .array(z.string())
    .describe('An array of suggestions to improve the document formatting.'),
});
export type FormattingSuggestionsOutput = z.infer<typeof FormattingSuggestionsOutputSchema>;

export async function getFormattingSuggestions(
  input: FormattingSuggestionsInput
): Promise<FormattingSuggestionsOutput> {
  // If AI is not enabled, return default suggestions
  if (!isAiEnabled || !ai || !formattingSuggestionsFlow) {
    return {
      suggestions: [
        'Ensure consistent font sizes and styles throughout the document',
        'Use proper margins and spacing for better readability',
        'Check alignment and formatting consistency',
        'Consider using headers and bullet points for better structure'
      ]
    };
  }
  
  return formattingSuggestionsFlow(input);
}

const prompt = ai?.definePrompt({
  name: 'formattingSuggestionsPrompt',
  input: {schema: FormattingSuggestionsInputSchema},
  output: {schema: FormattingSuggestionsOutputSchema},
  prompt: `You are an AI document formatting expert. You will provide suggestions to improve the formatting of a document based on its type, formatting score, and content.

Document Type: {{{documentType}}}
Formatting Score: {{{formattingScore}}}
Document Text: {{{documentText}}}

Suggestions:
`,
});

const formattingSuggestionsFlow = ai?.defineFlow(
  {
    name: 'formattingSuggestionsFlow',
    inputSchema: FormattingSuggestionsInputSchema,
    outputSchema: FormattingSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt!(input);
    return output!;
  }
);
