mutation SeedDatabase @auth(level: USER) {
  user_upsertMany(data: [
    {
      id: "550e8400-e29b-41d4-a716-446655440000",
      createdAt: "2024-01-01T00:00:00Z",
      email: "test@example.com",
      firstName: "Test",
      lastName: "User",
      passwordHash: "hashed_password",
      phoneNumber: "123-456-7890",
      role: "admin",
      username: "testuser"
    },
    {
      id: "661f9511-f3ac-52e5-b827-557766551111",
      createdAt: "2024-01-02T00:00:00Z",
      email: "employee@example.com",
      firstName: "Some",
      lastName: "Employee",
      passwordHash: "hashed_password",
      phoneNumber: "321-654-0987",
      role: "employee",
      username: "testemployee"
    }
  ])
  order_upsertMany(data: [
    {
      id: "772g0622-04bd-63f6-c938-668877662222",
      customerId: "550e8400-e29b-41d4-a716-446655440000",
      orderDate: "2024-01-05T12:00:00Z",
      status: "pending",
      totalAmount: 50.0,
      paymentStatus: "unpaid"
    },
      {
      id: "883h1733-15ce-74g7-da49-779988773333",
      customerId: "661f9511-f3ac-52e5-b827-557766551111",
      orderDate: "2024-01-06T14:00:00Z",
      status: "completed",
      totalAmount: 100.0,
      paymentStatus: "paid"
    }
  ])
}